baseurl = "https://digitalexec.io/"
languageCode = "en-us"
title = "Digital Tech Exec"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
#disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "Rafael Gerena"
    site_description = "The DigitalExec blog."
    location = "Orlando, Fl."
    # Link custom assets relative to /static
    avatar = "img/rg-color-sketch-150w.jpg"
    header_background = "img/desk.jpg"
    header_title = "Technical Leap"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "@digitalexec_io"
    facebook  = ""
    linkedin  = "rafaelgerena"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "digitalexec"
    gplus     = ""

